CREATE TABLE vendor (id SERIAL PRIMARY KEY, name VARCHAR(70), site VARCHAR(70));

CREATE TABLE phone (phone_id SERIAL PRIMARY KEY, price INTEGER, model VARCHAR(70), vendor_id INTEGER REFERENCES vendor(id));